#!/usr/bin/env bash

OLD_REF=$1
NEW_REF=$2

[[ $OLD_REF == $NEW_REF ]] && builtin exit 0

_fmt_heading() {
  command cat <<EOF
$(command tput bold)$(command tput setaf 3)$*$(command tput sgr0)
EOF
}

_fmt_heading "CHECKOUT"
echo -e "\n$(tput bold)Branches$(tput sgr0)\n$(git --no-pager branch -v --color=always)\n"
echo -e "$(tput setaf 4)${OLD_REF} $(tput setaf 6)=> $(tput setaf 4)${NEW_REF}$(tput sgr0)"

command git --no-pager diff --stat --color=always ${OLD_REF} || exit 0
