#!/usr/bin/env python
# -*- coding: utf-8 -*-

# SCRIPT OUTLINE
# --------------
#
#   NOTE: the name is short on purpose, for easy access feel free to rename.
#
# FUNCTION
# --------
# look recursively in the dir pointed to by the `look_in` variable for a file
# that matches arguments (feel free to provide many) provided in the command
# line. They are converted to a string and matched against all files (not
# paths!) in the dir and dirs below it.
#
# If neither of the scores obtained from levenshtein distance is above
# `threshold` variable, then $EDITOR is opened with a new file (if in the
# command line you provided a few words, they will be joined into a single file
# name).
#
# USAGE EXAMPLES  : n arg1 [arg2, arg3 ... ]
# --------------
# n feedback assessment
# n todolist.rst
# n operating-systems.rst
#
# DEPENDENCIES
# --------------
# python 3.5
# fuzzywuzzy (3rd party module)

import argparse
import glob
import os
import re
from fuzzywuzzy.fuzz import ratio
import subprocess
import functools


parser = argparse.ArgumentParser()

parser.add_argument('file', nargs='+')

args = parser.parse_args()

# -------------------------------------------
# CUSTOMIZE
threshold = 35

# CUSTOMIZE
prefered_extension = '.rst'

# CUSTOMIZE
look_in = '~/Notes/'
# -------------------------------------------

look_in = os.path.expandvars(os.path.expanduser(look_in))

alternative = "".join(args.file) + prefered_extension


stringified = "".join(map(lambda x: x + " ", args.file)) if len(args.file) > 1 else args.file[0]

notes = [
    i
    for i in glob.glob(
        os.path.expanduser(os.path.join(look_in, '**')), recursive=True)
    if re.compile('\.(md)|(rst)|(org)|(txt)|(textile)$').search(i)
]

reduced = functools.reduce(
    lambda x, y: x if ratio(x, stringified) > ratio(y, stringified) else y,
    [os.path.basename(i) for i in notes])

subprocess.run([
    os.path.expandvars('${EDITOR}'),
    notes[[os.path.basename(i) for i in notes].index(reduced)]
    if ratio(reduced, stringified) >= threshold else os.path.join(look_in, alternative)
])
