# Standard Library
from enum import Enum, auto, unique
# import types for static typing (mypy, pycharm etc)
from typing import Set, Text

# List of all availible configuration for MathJax.
# This is used to later check if the chosen config is valid.
MATHJAX_CONFS: Set[Text] = {
    "AM_CHTML",
    "AM_HTMLorMML",
    "AM_SVG",
    "MML_CHTML",
    "MML_HTMLorMML",
    "MML_SVG",
    "TeX-AMS-MML_HTMLorMML",
    "TeX-AMS-MML_SVG",
    "TeX-AMS_CHTML",
    "TeX-AMS_HTML",
    "TeX-AMS_SVG",
    "TeX-MML-AM_HTMLorMML",
    "TeX-MML-AM_SVG",
    "TeX-MML-AM_CHTML",
}


@unique
class Ext(Enum):
    ABBREVIATIONS = auto()
    ALL_SYMBOLS_ESCAPABLE = auto()
    ANGLE_BRACKETS_ESCAPABLE = auto()
    ASCII_IDENTIFIERS = auto()
    AUTO_IDENTIFIERS = auto()
    AUTOLINK_BARE_URIS = auto()
    BACKTICK_CODE_BLOCKS = auto()
    BLANK_BEFORE_BLOCKQUOTE = auto()
    BLANK_BEFORE_HEADER = auto()
    BRACKETED_SPANS = auto()
    CITATIONS = auto()
    COMPACT_DEFINITION_LISTS = auto()
    DEFINITION_LISTS = auto()
    EAST_ASIAN_LINE_BREAKS = auto()
    EMOJI = auto()
    EPUB_HTML_EXTS = auto()
    ESCAPED_LINE_BREAKS = auto()
    EXAMPLE_LISTS = auto()
    FANCY_LISTS = auto()
    FENCED_CODE_ATTRIBUTES = auto()
    FENCED_CODE_BLOCKS = auto()
    FENCED_DIVS = auto()
    FOOTNOTES = auto()
    FOUR_SPACE_RULE = auto()
    GFM_AUTO_IDENTIFIERS = auto()
    GRID_TABLES = auto()
    HARD_LINE_BREAKS = auto()
    HEADER_ATTRIBUTES = auto()
    IGNORE_LINE_BREAKS = auto()
    IMPLICIT_FIGURES = auto()
    IMPLICIT_HEADER_REFERENCES = auto()
    INLINE_CODE_ATTRIBUTES = auto()
    INLINE_NOTES = auto()
    INTRAWORD_UNDERSCORES = auto()
    LATEX_MACROS = auto()
    LINE_BLOCKS = auto()
    LINK_ATTRIBUTES = auto()
    LISTS_WITHOUT_PRECEDING_BLANKLINE = auto()
    LITERATE_HASKELL = auto()
    MARKDOWN_ATTRIBUTE = auto()
    MARKDOWN_IN_HTML_BLOCKS = auto()
    MMD_HEADER_IDENTIFIERS = auto()
    MMD_LINK_ATTRIBUTES = auto()
    MMD_TITLE_BLOCK = auto()
    MULTILINE_TABLES = auto()
    NATIVE_DIVS = auto()
    NATIVE_SPANS = auto()
    OLD_DASHES = auto()
    PANDOC_TITLE_BLOCK = auto()
    PIPE_TABLES = auto()
    RAW_ATTRIBUTE = auto()
    RAW_HTML = auto()
    RAW_TEX = auto()
    SHORTCUT_REFERENCE_LINKS = auto()
    SIMPLE_TABLES = auto()
    SMART = auto()
    SPACE_IN_ATX_HEADER = auto()
    SPACED_REFERENCE_LINKS = auto()
    STARTNUM = auto()
    STRIKEOUT = auto()
    SUBSCRIPT = auto()
    SUPERSCRIPT = auto()
    TABLE_CAPTIONS = auto()
    TEX_MATH_DOLLARS = auto()
    TEX_MATH_DOUBLE_BACKSLASH = auto()
    TEX_MATH_SINGLE_BACKSLASH = auto()
    YAML_METADATA_BLOCK = auto()


@unique
class LongOpt(Enum):
    ABBREVIATIONS = auto()
    ASCII = auto()
    ATX_HEADERS = auto()
    BASE_HEADER_LEVEL = auto()
    BASH_COMPLETION = auto()
    BIBLATEX = auto()
    BIBLIOGRAPHY = auto()
    CITATION_ABBREVIATIONS = auto()
    COLUMNS = auto()
    CSL = auto()
    CSS = auto()
    DATA_DIR = auto()
    DEFAULT_IMAGE_EXTENSION = auto()
    DPI = auto()
    DUMP_ARGS = auto()
    EMAIL_OBFUSCATION = auto()
    EOL = auto()
    EPUB_CHAPTER_LEVEL = auto()
    EPUB_COVER_IMAGE = auto()
    EPUB_EMBED_FONT = auto()
    EPUB_METADATA = auto()
    EPUB_SUBDIRECTORY = auto()
    EXTRACT_MEDIA = auto()
    FAIL_IF_WARNINGS = auto()
    FILE_SCOPE = auto()
    FILTER = auto()
    GLADTEX = auto()
    HIGHLIGHT_STYLE = auto()
    HTML_Q_TAGS = auto()
    ID_PREFIX = auto()
    IGNORE_ARGS = auto()
    INCLUDE_AFTER_BODY = auto()
    INCLUDE_BEFORE_BODY = auto()
    INCLUDE_IN_HEADER = auto()
    INCREMENTAL = auto()
    INDENTED_CODE_CLASSES = auto()
    KATEX = auto()
    KATEX_STYLESHEET = auto()
    LISTINGS = auto()
    LIST_EXTENSIONS = auto()
    LIST_HIGHLIGHT_LANGUAGES = auto()
    LIST_HIGHLIGHT_STYLES = auto()
    LIST_INPUT_FORMATS = auto()
    LIST_OUTPUT_FORMATS = auto()
    LOG = auto()
    LUA_FILTER = auto()
    MATHJAX = auto()
    MATHML = auto()
    METADATA = auto()
    NATBIB = auto()
    NO_HIGHLIGHT = auto()
    NUMBER_OFFSET = auto()
    NUMBER_SECTIONS = auto()
    PDF_ENGINE = auto()
    PDF_ENGINE_OPT = auto()
    PRESERVE_TABS = auto()
    PRINT_DEFAULT_DATA_FILE = auto()
    PRINT_HIGHLIGHT_STYLE = auto()
    QUIET = auto()
    REFERENCE_DOC = auto()
    REFERENCE_LINKS = auto()
    REFERENCE_LOCATION = auto()
    REQUEST_HEADER = auto()
    RESOURCE_PATH = auto()
    SECTION_DIVS = auto()
    SELF_CONTAINED = auto()
    SLIDE_LEVEL = auto()
    STANDALONE = auto()
    STRIP_COMMENTS = auto()
    STRIP_EMPTY_PARAGRAPHS = auto()
    SYNTAX_DEFINITION = auto()
    TAB_STOP = auto()
    TEMPLATE = auto()
    TITLE_PREFIX = auto()
    TOC = auto()
    TOC_DEPTH = auto()
    TOP_LEVEL_DIVISION = auto()
    TRACK_CHANGES = auto()
    VARIABLE = auto()
    VERBOSE = auto()
    WEBTEX = auto()
    WRAP = auto()


@unique
class CodeStyle(Enum):
    BREEZEDARK = auto()
    ESPRESSO = auto()
    HADDOCK = auto()
    KATE = auto()
    MONOCHROME = auto()
    PYGMENTS = auto()
    TANGO = auto()
    ZENBURN = auto()


@unique
class ToFmt(Enum):
    ASCIIDOC = auto()
    BEAMER = auto()
    COMMONMARK = auto()
    CONTEXT = auto()
    DOCBOOK = auto()
    DOCBOOK4 = auto()
    DOCBOOK5 = auto()
    DOCX = auto()
    DOKUWIKI = auto()
    DZSLIDES = auto()
    EPUB = auto()
    EPUB2 = auto()
    EPUB3 = auto()
    FB2 = auto()
    GFM = auto()
    HADDOCK = auto()
    HTML = auto()
    HTML4 = auto()
    HTML5 = auto()
    ICML = auto()
    JATS = auto()
    JSON = auto()
    LATEX = auto()
    MAN = auto()
    MARKDOWN = auto()
    MARKDOWN_GITHUB = auto()
    MARKDOWN_MMD = auto()
    MARKDOWN_PHPEXTRA = auto()
    MARKDOWN_STRICT = auto()
    MEDIAWIKI = auto()
    MS = auto()
    MUSE = auto()
    NATIVE = auto()
    ODT = auto()
    OPENDOCUMENT = auto()
    OPML = auto()
    ORG = auto()
    PLAIN = auto()
    REVEALJS = auto()
    RST = auto()
    RTF = auto()
    S5 = auto()
    SLIDEOUS = auto()
    SLIDY = auto()
    TEI = auto()
    TEXINFO = auto()
    TEXTILE = auto()
    ZIMWIKI = auto()


@unique
class FromFmt(Enum):
    COMMONMARK = auto()
    CREOLE = auto()
    DOCBOOK = auto()
    DOCX = auto()
    EPUB = auto()
    GFM = auto()
    HADDOCK = auto()
    HTML = auto()
    JSON = auto()
    LATEX = auto()
    MARKDOWN = auto()
    MARKDOWN_GITHUB = auto()
    MARKDOWN_MMD = auto()
    MARKDOWN_PHPEXTRA = auto()
    MARKDOWN_STRICT = auto()
    MEDIAWIKI = auto()
    MUSE = auto()
    NATIVE = auto()
    ODT = auto()
    OPML = auto()
    ORG = auto()
    RST = auto()
    T2T = auto()
    TEXTILE = auto()
    TIKIWIKI = auto()
    TWIKI = auto()
    VIMWIKI = auto()
