#!/usr/bin/env bash

# Regular expression to match against the commit message.
validator_regexp='[A-Z][-A-Za-z,.:;_]+'

# If it doesn't match, don't allow to commit!
# Allow only prinatble characters and spaces
# Begin with capitalized word, a end with a dot.
if [[ ! $(head -n 1 $1) =~ [A-Z][[:print:][:space:]]+\.$ ]]; then
	cat <<EOF

[ERROR] The commit message does not adhere to standard format.

THE MESSAGE 
-----------
$(cat $0)

RULES
-----
- capitalize entries 
- end with a dot
- use printable characters

Please fix it before re-comitting.

EOF
	exit 1
else
	cat $1 | grep -E -v  '^#' | fmt --uniform-spacing > /tmp/formatted_commit_msg.txt 
	cat /tmp/formatted_commit_msg.txt > $1
	cat <<EOF

The following commit message has been subitted

$(cat $1)

EOF
fi

