sy match cOpAround "\v(\=\=|!\=|\<\=|\>\=|\&\&?|\<\<|\>\>|\=|!|:|\<|\>|\+|\*)"
hi link cOpAround Operator
sy match cFunct "\v(\w+)\(@="
hi link cFunct Function
hi link cStructure Statement
sy match cBracket "\v\[|\]"
hi link cBracket Delimiter
sy match cBrace "\v\{|\}"
hi link cBrace Delimiter
